### ISSUE TITLE
Typescript Support

### ISSUE THREAD

**Issue by MV88** [infodusha/react-hook-size#3]
Hello!

I'm trying to use this in a project where i use Typescript.
but i get this compile error:

```
import React, {useRef} from 'react';
import * as ReactDOM from 'react-dom';
import { useSize } from 'react-hook-size';
```

```
C://....../node_modules/react-hook-size/dist/index.d.ts
(1,19): Cannot find module 'react'.
```

**Comment by infodusha** [comment]
@MV88 Hey! Can you please create an example repo?

**Comment by infodusha** [comment]
Just created repo with [this instruction](https://www.typescriptlang.org/docs/handbook/react-&-webpack.html). All worked correctly, maybe you missed something?

**Comment by MV88** [comment]
> @MV88 Hey! Can you please create an example repo?

i'll try, but i was working on a private project and probably is related to its configuration.
i'll also give a try to the instructions you linked, thanks

**Comment by infodusha** [comment]
@MV88 have a look on externals from link above:
```
externals: {
    react: "React",
    "react-dom": "ReactDOM"
}
```
Maybe it is what you are looking for?
